config/routes.rb
Rdb::Application.routes.draw do |map|
  resources :machine_statuses

  get "machine_types/free"
  resources :machine_types

  get 'bookings/specific_machines' => 'bookings#specific_machines'
  get 'bookings/deleted' => 'bookings#deleted'
  get 'bookings/expired' => 'bookings#expired'
  get 'bookings/future'  => 'bookings#future'
  resources :bookings

  get "machines/used_by"
  get "machines/general_purpose"
  get "machines/index"

  match 'admin' => 'admin#index'

  root :to => "bookings#index"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
   # WARNING: validations are run in order of appereance!
   
   belongs_to :user
   belongs_to :modifier, :class_name => "User", :foreign_key => "modified_by"
   has_many :reservations, :dependent => :destroy

   # User verification, must always be present!
   # user vs user_id:
   # http://stackoverflow.com/questions/3755828/ruby-on-rails-question-about-validates-presence-of
   validates_presence_of :user, :presence => true, :message => "User missing"
   validates_associated  :user

   # allow submit of nodes_count hash from the view
   attr_writer :nodes_count

   # allow direct creation of reservations
   accepts_nested_attributes_for :reservations

   validates_presence_of :begin
   validates_presence_of :end

   validate :begin_lt_end
   validate :has_one_or_more_reservations

   before_validation :create_reservations

   def has_one_or_more_reservations
      errors[:base] << "No machine selected" if (reservations.nil? or reservations.empty?)
   end

   def nodes_count(id=nil)
      # requested a specific nodes count?
      if id
         if @nodes_count.nil?
            0
         else
            @nodes_count[id.to_s]
         end
      else
         @nodes_count
      end
   end

   # depends on user_name=
   def user_name
      user_id ? User.find(user_id).name : ""
   end

   def user_name=(input)
      userexists=User.find_by_name(input)
      if userexists 
         self.user_id=userexists.id
      end
   end

   # depends on begin= and end=
   def begin_lt_end
      errors[:base] << "End should be after begin." if (self.begin >= self.end)
   end

   # return "current" booking time: now + 1 day
   def Booking.now
      dt = DateTime.now

      { :begin => dt, :end => dt + 1.day }
   end

   # Deleted bookings
   def Booking.deleted
      Booking.where :existing => false
   end

   def create_reservations
     # Mark booking existing (vs. deleted)
      machines = Machine.all
      machine_types = MachineType.all

      # Locate machines, depends on nodes_count=
      machines_to_book = []

      # Search for nodes if a count is submitted (vs. node ids submitted)
      if nodes_count
         nodes_count.each_pair do |type, count|
            typename = MachineType.find(type).name

            count = count.to_i
            all_machines = MachineType.find(type).machines

            if count > all_machines.count
               errors[:base] << "Trying to book more " + typename + "s than existing."
            else
               reservable_machines_count = 0 
               all_machines.each do |machine|
                  break if count == reservable_machines_count

                  if machine.is_free?({:begin => self.begin, :end => self.end})
                     reservable_machines_count += 1
                     machines_to_book << machine
                  end 
               end 

               if count != reservable_machines_count
                  errors[:base] <<"Only " + reservable_machines_count.to_s + " " + MachineType.find(type).name + "(s) available at the choosen date (#{count.to_s} requested)."

                  # be nice to the user and set the count to what is available
                  nodes_count[type] = reservable_machines_count
               end 
            end 
         end 

         # Setup REAL reservations independent of previous errors
         # (they cause abort anyway and we do not trigger the "no machines booked"
         # message
         self.reservations = []
         machines_to_book.each do |m|
            self.reservations << Reservation.new(:machine_id => m.id)
         end
      end
   end

   scope :current,
      where("existing = :active AND begin <= :dt AND end >= :dt", {
         :dt => DateTime.now,
         :active => true
         })

   scope :expired,
      where("existing = :active AND end < :dt", {
         :dt => DateTime.now,
         :active => true
         })

   scope :future,
      where("existing = :active AND begin > :dt", {
         :dt => DateTime.now,
         :active => true
         })
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

   @@default_period = 6.days

  # GET /bookings
  # GET /bookings.xml
  def index
    @bookings = Booking.current
    @btitle = "Current"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookings }
    end
  end

  def deleted
    @bookings = Booking.deleted
    @btitle = "Deleted"

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @bookings }
    end
  end

  def expired
    @bookings = Booking.expired
    @btitle = "Expired"

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @bookings }
    end
  end

  def future
    @bookings = Booking.future
    @btitle = "Future"

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @bookings }
    end
  end

  def specific_machines
    @booking = Booking.new
    @booking.reservations.build
    @booking.begin = DateTime.now
    @booking.end = @booking.begin + @@default_period

    @types = MachineType.all
    @reservations = Reservation.new
    @typelist = {}
    @i = 0
    @max = 0

    @types.each do |type|
      @typelist[type[:name]] = type.machines
      if @typelist[type[:name]].length > @max
         @max = @typelist[type[:name]].length
      end
    end
      
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @booking }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.xml
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.xml
  def new
    @booking = Booking.new
    @booking.reservations.build
    @machines = Machine.all
    @machine_types = MachineType.all
    @booking.begin = DateTime.now
    @booking.end = @booking.begin + @@default_period
    @hints = []

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
  end

   # POST /bookings
   # POST /bookings.xml
   def create

      # setup passed values
      @booking = Booking.new(params[:booking])
      @booking.user_id = session[:user_id]
      @nodes_count = params[:booking][:nodes_count]

      puts "session/user: " + @booking.user_id.to_s

      # Mark booking existing (vs. deleted)
      @booking.existing = true

       @machines = Machine.all
       @machine_types = MachineType.all
# 
#       # Locate machines, depends on nodes_count=
#       @machines_to_book = []
# 
#       # Search for nodes if a count is submitted (vs. node ids submitted)
#       if @nodes_count
#          @nodes_count.each_pair do |type, count|
#             typename = MachineType.find(type).name
# 
#             count = count.to_i
#             all_machines = MachineType.find(type).machines
# 
#             if count > all_machines.count
#                @booking.errors[:base] << "Trying to book more " + typename + "s than existing."
#             else
#                reservable_machines_count = 0 
#                all_machines.each do |machine|
#                   break if count == reservable_machines_count
# 
#                   if machine.is_free?({:begin => @booking.begin, :end => @booking.end})
#                      reservable_machines_count += 1
#                      @machines_to_book << { :machine_id => machine.id }
#                   end
#                end 
# 
#                if count != reservable_machines_count
#                   @booking.errors.add(:base, "Only " + reservable_machines_count.to_s + " " + MachineType.find(type).name + "(s) available at the choosen date.")
# 
#                   # be nice to the user and set the count to what is available
#                   @nodes_count[type] = reservable_machines_count
# 
#                   puts "CANNOT SATISFY COUNT"
#                   puts @booking.errors[:base]
#                end
#             end
#          end
# 
#          @booking.reservations_attributes = @machines_to_book
#       else
#          @booking.errors[:base] << "Zero machines selected"
#       end
# 
#       puts "isvalid? " + @booking.valid?.to_s
#       puts "size " + @booking.errors.size.to_s
#       puts "errors " + @booking.errors.to_s
# 
      respond_to do |format|
         if @booking.save
            format.html { redirect_to(@booking, :notice => 'Booking successfully created.') }
            format.xml  { render :xml => @booking, :status => :created, :location => @booking }
         else
            format.html { render :action => "new" }
            format.xml  { render :xml => @booking.errors, :status => :unprocessable_entity }
         end
      end
   end

  # PUT /bookings/1
  # PUT /bookings/1.xml
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to(@booking, :notice => 'Booking was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @booking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.xml
  def destroy
    @booking = Booking.find(params[:id])

    @booking.modified_by = session[:user_id]
    @booking.existing = false

    respond_to do |format|
      if @booking.update_attributes(@booking)
        format.html { redirect_to(bookings_url, :notice => 'Booking ' + @booking.id.to_s + ' was successfully deleted.') }
        format.xml  { head :ok }
      else
         # FIXME: do some sensible foo here
        format.html { render :action => "edit" }
        format.xml  { render :xml => @booking.errors, :status => :unprocessable_entity }
      end
    end
    #respond_to do |format|
    #  format.html { redirect_to(bookings_url) }
    #  format.xml  { head :ok }
    #end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_footer.erb
<p><%= link_to 'User overview', users_path %>
<p>Admin (should be made secure):
<br><%= link_to 'Machine overview', machines_path %>
<br><%= link_to 'Machine type overview', machine_types_path %>

<p>Debug (should be removed later):
<br><%= link_to 'Reservation overview', reservations_path %>
</p>

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
<%= render :partial => "formheader", :locals => { :booking => @booking, :f => f } %>

<div class=recordset>
<table>

<thead>
   <tr class="header">
      <th>Book</th>
      <th>Bookable (*)</th>
      <th>Type</th>
      <th>CPU</th>
      <th>Cores</th>
      <th>RAM</th>
   </tr>
</thead>
<tbody>
   <% @machine_types.each do |machine_type| %>
      <tr class="entry">
         <td><%= text_field_tag "booking[nodes_count][" + machine_type.id.to_s + "]",
                                 @booking.nodes_count(machine_type.id), :size => 2 %></td>
         <td><%= machine_type.bookable %></td>
         <td><%= machine_type.name %></td>
         <td><%= machine_type.cpu_type %></td>
         <td><%= machine_type.cores %></td>
         <td><%= machine_type.ram_gib %></td>
      </tr>
   <% end %>
</table>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>

<%end%>

app/views/bookings/_formheader.html.erb
  <% if @booking.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
    <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :begin %><br />
    <%= f.datetime_select :begin %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>

app/views/bookings/_header.erb
<p>
<%= link_to 'User management', users_path %>
<br><%= link_to 'Currently free machines', machine_types_free_path %>
<br><%= link_to 'Current machine users', machines_used_by_path %>
</p>

app/views/bookings/dead.html.erb
<h2>Deleted Bookings</h2>
<p class="notice"><%= notice %></p>
<div class="recordset">

<table>
<thead>
  <tr>
    <th>User</th>
    <th>Begin</th>
    <th>End</th>
    <th>Machines</th>
    <th>Deleting user</th>
  </tr>
</thead>

<tbody>
<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.user.name %></td>
    <td><%= booking.begin %></td>
    <td><%= booking.end %></td>
    <td><% booking.reservations.each do |reservation| %>
    <%= reservation.machine.name %>
    <%end%></td>
    <td><%= booking.modifier.name %></td>
  </tr>
<% end %>
</tbody>
</table>

</div>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

Is not supported. Please delete and recreate.

<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h2><%= @btitle %> Bookings</h2>
<p class="notice"><%= notice %></p>
<div class="recordset">

<table>
<thead>
  <tr>
    <th>ID</th>
    <th>User</th>
    <th>Comment</th>
    <th>Begin</th>
    <th>End</th>
    <th>Machines</th>
    <th>Modifier</th>
    <th>Actions</th>
  </tr>
</thead>

<tbody>
<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.id %></td>
    <td><%= booking.user.name %></td>
    <td><%= booking.comment %></td>
    <td><%= booking.begin %></td>
    <td><%= booking.end %></td>
    <td><% booking.reservations.each do |reservation| %>
    <%= reservation.machine.name %>
    <%end%></td>
    <td><%= booking.modifier ? booking.modifier.name : "" %></td>
    <td><%= link_to '[show]', booking %>
    <%= link_to '[delete]', booking, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

</div>

app/views/bookings/new.html.erb
<h2>New booking</h2>

<%= render 'form' %>

app/views/bookings/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  User <b><%= @booking.user.name %></b> booked the following machines
  as booking <b><%= @booking.id %></b> from <b><%= @booking.begin %></b> until
  <b><%= @booking.end %></b>
  <ul>
  <% @booking.reservations.each do |reservation| %>
  <li><%= reservation.machine.name %>
  <%end%>
  </ul>
  <p><b>Short list:</b>
  <% @booking.reservations.each do |reservation| %>
  <%= reservation.machine.name %>
  <%end%>
</p>


<%= link_to 'Back', bookings_path %>

app/views/bookings/specific_machines.erb
<h2>New booking (specific machines)</h2>

<%= form_for(@booking) do |f| %>
<%= render :partial => "formheader", :locals => { :booking => @booking, :f => f } %>

<div class=recordset>
<table>

<thead>
   <tr class="header">
      <th>Cluster</th>
      <% @i=1 %>
      <% while @i <= @max %>
      <th><%= sprintf("%0.2d",@i) %></th>
      <% @i=@i+1 %>
      <% end %>
   </tr>
</thead>
<tbody>
<% @i=0 %>
<%= f.fields_for :reservations do |r| %>
<% @typelist.each_pair do |name, machines| %>
   <tr>
      <th><%= name %></th>
      <% machines.each do |machine| %>
        <td><%= check_box_tag "booking[reservations_attributes][" + @i.to_s + "][machine_id]", machine.id %></td>
        <% @i = @i+1%>
      <% end %>
      <% while @i < @max %>
        <td> &nbsp;</td> <% @i = @i+1%>
      <%end%>
      <%@i=0%>
   </tr>
<% end %>
<% end %>
</tbody>
</table>
</div>
<div class="actions">
 <%= f.submit %>
</div>

<%end%>