config/routes.rb
Rdb::Application.routes.draw do |map|
  resources :machine_statuses

  get "machine_types/free"
  resources :machine_types

  get 'bookings/specific_machines' => 'bookings#specific_machines'
  get 'bookings/deleted' => 'bookings#deleted'
  get 'bookings/expired' => 'bookings#expired'
  get 'bookings/future'  => 'bookings#future'
  resources :bookings

  get "machines/used_by"
  get "machines/general_purpose"
  get "machines/index"

  match 'admin' => 'admin#index'

  root :to => "bookings#index"

end

app/controllers/machine_statuses_controller.rb
class MachineStatusesController < ApplicationController
  # GET /machine_statuses
  # GET /machine_statuses.xml
  def index
    @machine_statuses = MachineStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machine_statuses }
    end
  end

  # GET /machine_statuses/1
  # GET /machine_statuses/1.xml
  def show
    @machine_status = MachineStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine_status }
    end
  end

  # GET /machine_statuses/new
  # GET /machine_statuses/new.xml
  def new
    @machine_status = MachineStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine_status }
    end
  end

  # GET /machine_statuses/1/edit
  def edit
    @machine_status = MachineStatus.find(params[:id])
  end

  # POST /machine_statuses
  # POST /machine_statuses.xml
  def create
    @machine_status = MachineStatus.new(params[:machine_status])

    respond_to do |format|
      if @machine_status.save
        format.html { redirect_to(@machine_status, :notice => 'Machine status was successfully created.') }
        format.xml  { render :xml => @machine_status, :status => :created, :location => @machine_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @machine_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /machine_statuses/1
  # PUT /machine_statuses/1.xml
  def update
    @machine_status = MachineStatus.find(params[:id])

    respond_to do |format|
      if @machine_status.update_attributes(params[:machine_status])
        format.html { redirect_to(@machine_status, :notice => 'Machine status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @machine_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_statuses/1
  # DELETE /machine_statuses/1.xml
  def destroy
    @machine_status = MachineStatus.find(params[:id])
    @machine_status.destroy

    respond_to do |format|
      format.html { redirect_to(machine_statuses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/machine_statuses_helper.rb
module MachineStatusesHelper
end

app/views/machine_statuses/_form.html.erb
<%= form_for(@machine_status) do |f| %>
  <% if @machine_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine_status.errors.count, "error") %> prohibited this machine_status from being saved:</h2>

      <ul>
      <% @machine_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machine_statuses/edit.html.erb
<h1>Editing machine_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine_status %> |
<%= link_to 'Back', machine_statuses_path %>

app/views/machine_statuses/index.html.erb
<h1>Listing machine_statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machine_statuses.each do |machine_status| %>
  <tr>
    <td><%= machine_status.name %></td>
    <td><%= link_to 'Show', machine_status %></td>
    <td><%= link_to 'Edit', edit_machine_status_path(machine_status) %></td>
    <td><%= link_to 'Destroy', machine_status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Machine status', new_machine_status_path %>

app/views/machine_statuses/new.html.erb
<h1>New machine_status</h1>

<%= render 'form' %>

<%= link_to 'Back', machine_statuses_path %>

app/views/machine_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @machine_status.name %>
</p>


<%= link_to 'Edit', edit_machine_status_path(@machine_status) %> |
<%= link_to 'Back', machine_statuses_path %>