config/routes.rb
Rdb::Application.routes.draw do |map|
  resources :machine_statuses

  get "machine_types/free"
  resources :machine_types

  get 'bookings/specific_machines' => 'bookings#specific_machines'
  get 'bookings/deleted' => 'bookings#deleted'
  get 'bookings/expired' => 'bookings#expired'
  get 'bookings/future'  => 'bookings#future'
  resources :bookings

  get "machines/used_by"
  get "machines/general_purpose"
  get "machines/index"

  match 'admin' => 'admin#index'

  root :to => "bookings#index"

end

app/models/machine.rb
class Machine < ActiveRecord::Base

   belongs_to  :machine_status
   belongs_to  :machine_type
   has_many    :reservations, :dependent => :destroy
   has_many    :bookings, :through => :reservations

   validates :name, :uniqueness => true, :presence => true
   validates_associated :machine_type
   validates_associated :machine_status


   def is_booked?(dates)
      booked = nil

      bookings.each do |booking|
         # Old code: to check bookings
         # if (booking.begin <= dates[:begin] and booking.end > dates[:begin]) or
         #     (dates[:end] > booking.begin and dates[:end] <= booking.end)

      # Given:
      #  - begin and end of requested booking (dates[:begin], dates[:end]
      #  - begin and end of all existing bookings for the machine
      #  - new begin may be at the same time old expires (i.e. begin_new == end_old)
      #
      # Searched:
      # - any booking conflict
      #
      # Idea:
      #
      # - Does the new booking begin after our end?
         if (dates[:begin] > booking.end)
            #
            #  yes: no conflict possible with this booking
            #
            next
         else
         #
         # no: the booking can conflict with the current one
         #

            #
            # Does the booking end before our begin?
            #
            if (dates[:end] < booking.begin)
               #
               #  yes: no conflict possible with this booking
               #
               next
            else
               #
               #  no: new one begins before our end and
               #      new ones ends after our begin
               #      -----> conflict
               #
               
               # Verify that the booking still exists (i.e. not deleted)
               if booking.existing?
                  booked = booking
                  break
               end
            end
         end
      end

      booked
   end

   def is_free?(dates)
      if machine_status == MachineStatus.find_by_name("bookable")
         is_booked?(dates) ? false : true
      else
         false
      end
   end

   def used_by
      booking = is_booked? Booking.now

      if booking
         booking.user.name
      end
   end

   def general_purpose?
      machine_status == MachineStatus.find_by_name("general purpose")
   end

   # listing all general purpose - FIXME: why not scope?
   def Machine.general_purpose
      list = []
      Machine.all.each do |m|
         m.general_purpose? and list << m
      end

      list
   end

end

app/models/machine_type.rb
class MachineType < ActiveRecord::Base
   validates :name, :uniqueness => true

   validates_presence_of :ram_gib
   validates_presence_of :cores
   validates_presence_of :cpu_type
   validates_numericality_of :count, :greater_than_or_equal_to => 0, :only_integer => true

   has_many :machines, :dependent => :destroy

   accepts_nested_attributes_for :machines

   before_save :create_machines

   attr_accessor :machine_description

   @machines = []
   @machine_description = ""

   def count
      self.machines.count
   end
      
   def count=(input)
      @count=input
   end

   # autocreate, mostly used during seeding
   def create_machines
      i = 1
      self.machines = []
      status = MachineStatus.find_by_name("bookable")

      while i <= @count.to_i
         name = sprintf "%s%0.2d", self.name.downcase, i
         self.machines << Machine.new({ :name => name,
                                       :description => @machine_description,
                                       :machine_status => status
                                    })
         i += 1
      end 
   end

   # all those which COULD be bookable from status point of view
   def bookable
      count = 0
      machines.each do |m|
         if m.machine_status == MachineStatus.find_by_name("bookable")
            count += 1
         end
      end
      count
   end
      
   def free_machines
      count = 0
      dates = Booking.now

      machines.each do |machine|
         if machine.is_free?(dates)
            count += 1
         end
      end

      count
   end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  # GET /machines
  # GET /machines.xml
  def index
    @machines = Machine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machines }
    end
  end

  def general_purpose
    @machines = Machine.general_purpose

    respond_to do |format|
      format.html
      format.xml  { render :xml => @machines }
    end
  end

  # GET /machines/1
  # GET /machines/1.xml
  def show
    @machine = Machine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine }
    end
  end

  # GET /machines/new
  # GET /machines/new.xml
  def new
    @machine = Machine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine }
    end
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
  end

  # POST /machines
  # POST /machines.xml
  def create
    @machine = Machine.new(params[:machine])

    respond_to do |format|
      if @machine.save
        format.html { redirect_to(@machine, :notice => 'Machine was successfully created.') }
        format.xml  { render :xml => @machine, :status => :created, :location => @machine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /machines/1
  # PUT /machines/1.xml
  def update
    @machine = Machine.find(params[:id])

    respond_to do |format|
      if @machine.update_attributes(params[:machine])
        format.html { redirect_to(@machine, :notice => 'Machine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.xml
  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to(machines_url) }
      format.xml  { head :ok }
    end
  end

  def used_by
    @machines = Machine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machines }
    end
  end

end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>
    <ul>
    <% @machine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
   <%= collection_select(:machine, :machine_type_id, MachineType.all, :id, :name, {:prompt => true}) %>
  </div>
  <div class="field">
   <%= collection_select(:machine, :machine_status_id, MachineStatus.all, :id, :name, {:prompt => true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/general_purpose.html.erb
<h2>General purpose machines</h2>

<P>Short list:
<% @machines.each do |machine| %>
   <%= machine.name %>
<% end %>

<div class="recordset">
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Type</th>
  </tr>
</thead>
<tbody>

<% @machines.each do |machine| %>
  <tr>
    <td><%= machine.name %></td>
    <td><%= link_to machine.machine_type.name, machine_type_path(machine.machine_type_id) %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/machines/index.html.erb
<h1>Listing machines</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Used by?</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machines.each do |machine| %>
  <tr>
    <td><%= machine.name %></td>
    <td><%= machine.description %></td>
    <td><%= machine.machine_status.name %></td>
    <td><%= machine.used_by %></td>
    <td><%= link_to machine.machine_type.name, machine_type_path(machine.machine_type_id) %></td>
    <td><%= link_to 'Show', machine %></td>
    <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
    <td><%= link_to 'Destroy', machine, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/machines/new.html.erb
<h1>New machine</h1>

<%= render 'form' %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @machine.name %>
</p>

<p>
  <b>Description:</b>
  <%= @machine.description %>
</p>

<p>
  <b>Status:</b>
  <%= @machine.machine_status.name %>
</p>


<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>

app/views/machines/used_by.html.erb
<h2>Machines currently used</h2>

<div class="recordset">
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Used by</th>
  </tr>
</thead>
<tbody>

<% @machines.each do |machine| %>
   <% if machine.used_by %>
     <tr>
       <td><%= machine.name %></td>
       <td><%= link_to machine.machine_type.name, machine_type_path(machine.machine_type_id) %></td>
       <td><%= machine.used_by %></td>
     </tr>
   <% end %>
<% end %>
</tbody>
</table>
</div>