config/routes.rb
Rdb::Application.routes.draw do |map|
  resources :machine_statuses

  get "machine_types/free"
  resources :machine_types

  get 'bookings/specific_machines' => 'bookings#specific_machines'
  get 'bookings/deleted' => 'bookings#deleted'
  get 'bookings/expired' => 'bookings#expired'
  get 'bookings/future'  => 'bookings#future'
  resources :bookings

  get "machines/used_by"
  get "machines/general_purpose"
  get "machines/index"

  match 'admin' => 'admin#index'

  root :to => "bookings#index"

end

app/controllers/machine_types_controller.rb
class MachineTypesController < ApplicationController
  # GET /machine_types
  # GET /machine_types.xml
  def index
    @machine_types = MachineType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machine_types }
    end
  end

  # GET /machine_types/1
  # GET /machine_types/1.xml
  def show
    @machine_type = MachineType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine_type }
    end
  end

  # GET /machine_types/new
  # GET /machine_types/new.xml
  def new
    @machine_type = MachineType.new
    @count = 0

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine_type }
    end
  end

  # GET /machine_types/1/edit
  def edit
    @machine_type = MachineType.find(params[:id])
  end

  # POST /machine_types
  # POST /machine_types.xml
  def create
    @machine_type = MachineType.new(params[:machine_type])

      respond_to do |format|
         if @machine_type.save
            format.html { redirect_to(@machine_type, :notice => 'Machine type was successfully created.') }
            format.xml  { render :xml => @machine_type, :status => :created, :location => @machine_type }
         else
            format.html { render :action => "new" }
            format.xml  { render :xml => @machine_type.errors, :status => :unprocessable_entity }
         end
      end
   end

  # PUT /machine_types/1
  # PUT /machine_types/1.xml
  def update
    @machine_type = MachineType.find(params[:id])

    respond_to do |format|
      if @machine_type.update_attributes(params[:machine_type])
        format.html { redirect_to(@machine_type, :notice => 'Machine type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @machine_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_types/1
  # DELETE /machine_types/1.xml
  def destroy
    @machine_type = MachineType.find(params[:id])
    @machine_type.destroy

    respond_to do |format|
      format.html { redirect_to(machine_types_url) }
      format.xml  { head :ok }
    end
  end

  # GET/POST /machine_types/free
  def free
    @machine_types = MachineType.all

    respond_to do |format|
      format.html
      format.xml  { render :xml => @machine_types }
    end
  end

end

app/helpers/machine_types_helper.rb
module MachineTypesHelper
end

app/views/machine_types/_form.html.erb
<%= form_for(@machine_type) do |f| %>
  <% if @machine_type.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@machine_type.errors.count, "error") %> prohibited this machine_type from being saved:</h2>
    <ul>
    <% @machine_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ram_gib %><br />
    <%= f.text_field :ram_gib %>
  </div>
  <div class="field">
    <%= f.label :cores %><br />
    <%= f.text_field :cores %>
  </div>
  <div class="field">
    <%= f.label :cpu_type %><br />
    <%= f.text_field :cpu_type %>
  </div>
  <div class="field">
    <%= f.label :machine_count %><br />
    <%= f.text_field :count, :size => 2 %>
  </div>
  <div class="field">
    <%= f.label :machine_description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machine_types/edit.html.erb
<h1>Editing machine_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine_type %> |
<%= link_to 'Back', machine_types_path %>

app/views/machine_types/free.erb
<h2>Free machines</h2>

<div class="recordset">
<table>
<thead>
  <tr>
    <th>Free #</th>
    <th>Name</th>
    <th>Ram gib</th>
    <th>Cores</th>
    <th>Cpu type</th>
  </tr>
</thead>
<tbody>

<% @machine_types.each do |machine_type| %>
  <tr>
    <td><%= machine_type.free_machines %></td>
    <td><%= machine_type.name %></td>
    <td><%= machine_type.ram_gib %></td>
    <td><%= machine_type.cores %></td>
    <td><%= machine_type.cpu_type %></td>
  </tr>
<% end %>
</table>
</tbody>
</div>

app/views/machine_types/index.html.erb
<h1>Listing machine_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ram gib</th>
    <th>Cores</th>
    <th>Cpu type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machine_types.each do |machine_type| %>
  <tr>
    <td><%= machine_type.name %></td>
    <td><%= machine_type.ram_gib %></td>
    <td><%= machine_type.cores %></td>
    <td><%= machine_type.cpu_type %></td>
    <td><%= link_to 'Show', machine_type %></td>
    <td><%= link_to 'Edit', edit_machine_type_path(machine_type) %></td>
    <td><%= link_to 'Destroy', machine_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Machine type', new_machine_type_path %>

app/views/machine_types/new.html.erb
<h1>New machine_type</h1>

<%= render 'form' %>

<%= link_to 'Back', machine_types_path %>

app/views/machine_types/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @machine_type.name %>
</p>

<p>
  <b>Ram gib:</b>
  <%= @machine_type.ram_gib %>
</p>

<p>
  <b>Cores:</b>
  <%= @machine_type.cores %>
</p>

<p>
  <b>Cpu type:</b>
  <%= @machine_type.cpu_type %>
</p>


<%= link_to 'Edit', edit_machine_type_path(@machine_type) %> |
<%= link_to 'Back', machine_types_path %>